spring.application.name=users

# Database configuration
spring.r2dbc.url=r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.r2dbc.username=test
spring.r2dbc.password=test

spring.sql.init.mode=embedded

server.error.include-binding-errors=always
server.error.include-message=always

# logging.level.org.springframework.r2dbc=DEBUG
logging.level.io.r2dbc.h2=DEBUG

token.secret=F9k2Lm7Qr4Tz8Vb1Np6Yx3Cd5Gh9Jm2Pq7Rw4Su8Xn1Za6Bc3Df7Hg5Kt9Lp2Mv8
