spring.application.name=users

# Database configuration
spring.r2dbc.url=r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.r2dbc.username=test
spring.r2dbc.password=test

spring.sql.init.mode=embedded

server.error.include-binding-errors=always
server.error.include-message=always
